spring:
  data:
    redis:
      host: localhost
      port: 60823
  datasource:
    url: jdbc:mysql://localhost:3306/iam_keycloak
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8180/realms/tien #den tu realms nao // cai base cua khong gian realm trong keycloak
          jwk-set-uri: ${spring.security.oauth2.resource server.jwt.issuer-uri}/protocol/openid-connect/certs #biet public key de verify
iam:
  use-keycloak: true
  keycloak:
    realm: tien
    auth-server-url: http://localhost:8180
    client-id: tien_app
    client-secret: JKeoBFBJ7B2B8NvNTnUHfhM1kaZFua2s

jwt:
  secret: "NqoOR/41C1WWFKRKKX8+/E7V8VBepn+/pmFwfKP0GDOuVuwgtBslCeu3swN0KGp8nPYv/wEiLrc2z0Qra0uptOtJAFVOS+7Vju2sHbUae1U="
  expiration: 3600000

open:
  api:
    title: "KEYCLOAK_IAM_SERVICE"
    version: "v1.0.0"
    description: "manage with keycloak"
    url: "http://localhost:8081"
    description-server-url: "server-dev"

server:
  port: 8081
